# Generated by Django 3.2.5 on 2021-07-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=50, verbose_name='name')),
                ('title_2', models.CharField(max_length=50, verbose_name='contact')),
                ('text_1', models.TextField(verbose_name='text')),
                ('pub_time', models.TimeField(verbose_name='time')),
                ('pub_date', models.DateField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'Запросы',
                'verbose_name_plural': 'Запрос',
            },
        ),
    ]
