# Generated by Django 3.2.5 on 2021-07-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reqest', '0002_auto_20210725_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='pub_date',
            field=models.IntegerField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='user_request',
            name='pub_time',
            field=models.IntegerField(verbose_name='time'),
        ),
    ]
